name: online_shop
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  http: ^1.2.0
  nice_buttons: ^0.0.3
  flutter_svg: ^2.0.9
  animated_notch_bottom_bar: ^1.0.0
  cupertino_icons: ^1.0.2
  vibration: ^1.8.4
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.7
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_simple_calculator: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/img/
   

fonts:
   - family: Big
     fonts:
       - asset: assets/font/big.ttf
uses-material-design: true